# Generated by Django 4.2.16 on 2024-10-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Background Image')),
            ],
        ),
        migrations.CreateModel(
            name='StoryFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Position')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='story.story')),
            ],
        ),
    ]
